const GET_DEVICE_HOST = 'GET_DEVICE_HOST'
const GET_DEVICE_DEVICE = 'GET_DEVICE_DEVICE'
const GET_EXPIRE_INFO = 'GET_EXPIRE_INFO'
const GET_SHOW_ALARM = 'GET_SHOW_ALARM'
const GET_SHOW_VALUES = 'GET_SHOW_VALUES'

export{
   GET_DEVICE_HOST,
   GET_DEVICE_DEVICE,
   GET_EXPIRE_INFO,
   GET_SHOW_ALARM,
   GET_SHOW_VALUES,
}